run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - revive
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - gocognit
    - asciicheck
    - gofumpt
    - prealloc
    - predeclared
    - nilerr
    - exhaustive
    - exportloopref
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: modifies-parameter
      - name: unreachable-code

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
        - errcheck
        - gocognit
    
    # Exclude example files
    - path: examples/
      linters:
        - gosec
        - errcheck

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0