// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountCommentsByPost(ctx context.Context, postID int64) (int64, error)
	CountPosts(ctx context.Context) (int64, error)
	CountPublishedPosts(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id int64) error
	DeleteCommentsByPost(ctx context.Context, postID int64) error
	DeletePost(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPostBySlug(ctx context.Context, slug string) (Post, error)
	GetPostWithAuthor(ctx context.Context, id int64) (GetPostWithAuthorRow, error)
	GetPostsWithCommentCounts(ctx context.Context) ([]GetPostsWithCommentCountsRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCommentsByPost(ctx context.Context, postID int64) ([]ListCommentsByPostRow, error)
	ListCommentsByUser(ctx context.Context, userID int64) ([]Comment, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPostsByUser(ctx context.Context, userID int64) ([]Post, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error)
	ListUsers(ctx context.Context) ([]User, error)
	PublishPost(ctx context.Context, id int64) (Post, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
